#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
export GENERIC_SECRET_SCORE="${GENERIC_SECRET_SCORE:-0.8}"
export ENTROPY_THRESHOLD="${ENTROPY_THRESHOLD:-0.7}"
export ENABLE_GENERIC_SECRETS="${ENABLE_GENERIC_SECRETS:-false}"
export ENABLE_ENTROPY_PROXIMITY="${ENABLE_ENTROPY_PROXIMITY:-true}"
export FP_SUPPRESSION_MODE="${FP_SUPPRESSION_MODE:-enforce}"
export VENDOR_STRUCTURAL_SUPPRESSION="${VENDOR_STRUCTURAL_SUPPRESSION:-enforce}"
go run .
